apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fe
  labels:
   calc-metrics: fe
spec:
  jobLabel: calc-metrics
  selector:
    matchLabels:
      calc-metrics: fe
  namespaceSelector:
    matchNames:
    - calculations
  endpoints:
  - port: api-service
    interval: 20s