apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fact-deployment
  labels:
    app: fact
spec:
  selector:
    matchLabels:
      app: fact
  replicas: 2
  template:
    metadata:
      labels:
        app: fact
    spec:
      containers:
      - name: fact
        image: quay.io/tamarakaufler/factorial-service:v1alpha1
        imagePullPolicy: Never
        ports:
        - name: fact-service
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fact-service
spec:
  selector:
    app: fact
  ports:
  - port: 3000
    targetPort: fact-service
