apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: calculations
  labels:
    app: fe
spec:
  selector:
    matchLabels:
      app: fe
  replicas: 1
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: quay.io/tamarakaufler/fe-calculations:v1alpha1
        imagePullPolicy: Never
        ports:
        - name: fe-service
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: calculations
  labels:
    app: fe
    calc-metrics: fe
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  type: NodePort
  selector:
    app: fe
  ports:
  - port: 3000
    targetPort: fe-service
