apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fib-deployment
  labels:
    app: fib
spec:
  selector:
    matchLabels:
      app: fib
  replicas: 1
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib
        image: quay.io/tamarakaufler/fibonacci-service:v1alpha1
        imagePullPolicy: Never
        ports:
        - name: fib-service
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fib-service
spec:
  selector:
    app: fib
  ports:
  - port: 3000
    targetPort: fib-service
